### ISSUE TITLE
Support ISO-8601 dates

### ISSUE THREAD

**Issue by burnchar** [sujithravikumar/vacation-accrual-buddy#4]
The currently accepted date format is 04/28/18, which requires URL encoding and is region-centric.
The de facto internet standard (and ipso facto international standard) is ISO-8601, e.g. 2018-04-28 or 20180428. Besides following a global standard, these look better in URLs (e.g. https://vacationaccrual.azurewebsites.net/?StartDate=2018-04-29), are unambiguous as to day/month order, and support 4 digit years to prevent bugs when when this software is of course still in use 82 years from now. ;)

**Comment by sujithravikumar** [comment]
Agreed! I will work on the enhancement.

**Comment by sujithravikumar** [comment]
New patch applied.
